CC=gcc
CFLAGS=-O3 -Wall

hello: hello.c
		$(CC) $(CFLAGS) -o hello hello.c
printcl: printcl.c
		$(CC) $(CFLAGS) -o printcl printcl.c
readfile: readfile.c
		$(CC) $(CFLAGS) -o readfile readfile.c
clean:
		rm -f hello printcl readfile
